name: TestPlugin
main: com.gmail.tgdolan.bukkit.testplugin.TestPlugin
version: 1.0.0

commands: 
  basic:
    description: This is a demo command.
    usage: /basic [playerName]
    permission: TestPlugin.basic
    permission: You don't have TestPlugin.basic permission.